[package]
name = "poem_up_service"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

entity = { path ="../entity" }

thiserror = { version ="1.0" }